#!/usr/bin/env python3
"""Embed regenerated figures into main.docx before each Figure caption."""
import re
import shutil
from pathlib import Path

from docx import Document
from docx.shared import Inches

ROOT = Path(__file__).resolve().parent
MAIN = ROOT / "public" / "main.docx"
FIGURES = ROOT / "figures"

# Manuscript figure number -> generated asset stem (script naming != manuscript numbering)
FIGURE_FILES = {
    1: "Fig1_framework_overview",  # generated by generate_fig1.py (SiM protocol)
    2: "Fig2_missing_rate_robustness",
    3: "Fig4_temporal_validation",
    4: "Fig3_calibration_curves",
    5: "Fig5_downstream_bias",
}

FIG1_CAPTION = (
    "Figure 1. Overview of the statistical evaluation protocol for inferring missing contextual labels. "
    "CHNS provides complete T2 ground truth for internal validation; primary reporting focuses on binary "
    "Rural vs Urban discrimination under simulated label missingness, with multi-dimensional checks "
    "(missing-rate robustness, leave-one-year-out, distributional fidelity, calibration, comparators, "
    "and downstream effect preservation)."
)


def has_equation(element) -> bool:
    for node in element.iter():
        tag = node.tag.split("}")[-1] if "}" in node.tag else node.tag
        if tag in ("oMath", "oMathPara"):
            return True
    return False


def has_drawing(paragraph) -> bool:
    return bool(paragraph._element.findall(".//{http://schemas.openxmlformats.org/wordprocessingml/2006/main}drawing"))


def resolve_figure_path(stem: str | None) -> Path | None:
    if stem is None:
        return None
    for ext in (".png", ".tiff", ".tif", ".jpg"):
        p = FIGURES / f"{stem}{ext}"
        if p.exists():
            return p
    return None


def remove_existing_figure_images(doc: Document) -> None:
    """Remove orphaned or misplaced inline images (keep equations)."""
    to_clear = []
    for p in doc.paragraphs:
        if has_drawing(p) and not has_equation(p._element):
            to_clear.append(p)
    for p in to_clear:
        p._element.getparent().remove(p._element)


def update_fig1_caption(doc: Document) -> None:
    for p in doc.paragraphs:
        if p.text.strip().startswith("Figure 1.") and not has_equation(p._element):
            p.text = FIG1_CAPTION
            return


def embed_figures(doc: Document) -> int:
    embedded = 0
    for i, p in enumerate(doc.paragraphs):
        m = re.match(r"^Figure\s+(\d+)\.", p.text.strip())
        if not m:
            continue
        fig_num = int(m.group(1))
        img_path = resolve_figure_path(FIGURE_FILES.get(fig_num))
        if img_path is None:
            print(f"  WARNING: no file for Figure {fig_num}")
            continue
        prev = doc.paragraphs[i - 1] if i > 0 else None
        if prev is not None and has_drawing(prev):
            continue
        img_p = p.insert_paragraph_before("")
        img_p.alignment = 1  # center
        run = img_p.add_run()
        run.add_picture(str(img_path), width=Inches(6.2))
        embedded += 1
        print(f"  Embedded Figure {fig_num} <- {img_path.name}")
    return embedded


def main():
    backup = MAIN.with_suffix(".docx.pre-figures.bak")
    shutil.copy2(MAIN, backup)
    doc = Document(str(MAIN))
    remove_existing_figure_images(doc)
    update_fig1_caption(doc)
    n = embed_figures(doc)
    doc.save(str(MAIN))
    print(f"Embedded {n} figures in {MAIN}")
    print(f"Backup: {backup}")


if __name__ == "__main__":
    main()
